### Manual Calculation of evaluation metrics(Most Imp for offline Mcqs)

In [3]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
dtree=DecisionTreeClassifier(criterion='entropy')
dtree.fit(x_train,y_train)
y_pred=dtree.predict(x_test);
print(confusion_matrix(y_test,y_pred))

NameError: name 'x' is not defined

### Q 271

In [5]:
#  The task involves building a Decision Tree classifier to predict whether to play tennis based on weather conditions. The dataset 
# used for this task is the PlayTennis dataset, which contains information about various weather attributes such as outlook, 
# temperature, humidity, and wind, along with the corresponding decision to play tennis or not. Use PlayTennis.csv for dataset.

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/PlayTennis.csv');
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [12]:
x=df.drop(columns=['play']);
y=df['play']

x=pd.get_dummies(x);
# x

    windy  outlook_overcast  outlook_rainy  outlook_sunny  ...  temp_hot  temp_mild  humidity_high  humidity_normal
0   False             False          False           True  ...      True      False           True            False
1    True             False          False           True  ...      True      False           True            False
2   False              True          False          False  ...      True      False           True            False
3   False             False           True          False  ...     False       True           True            False
4   False             False           True          False  ...     False      False          False             True
5    True             False           True          False  ...     False      False          False             True
6    True              True          False          False  ...     False      False          False             True
7   False             False          False           True  ...     False       True           True            False
8   False             False          False           True  ...     False      False          False             True
9   False             False           True          False  ...     False       True          False             True
10   True             False          False           True  ...     False       True          False             True
11   True              True          False          False  ...     False       True           True            False
12  False              True          False          False  ...      True      False          False             True
13   True             False           True          False  ...     False       True           True            False

[14 rows x 9 columns]

In [13]:
dtree=DecisionTreeClassifier(criterion='entropy',max_depth=3)

In [14]:
dtree.fit(x,y)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [15]:
prediction=dtree.predict(x)
print(prediction)

['no' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'yes'
 'no']

### Q311) Desicion Tree For Diabetes

In [ ]:
#  Diabetes Prediction using Random Forest
# You are given a dataset diabetes.csv containing medical records of patients.
# The dataset includes predictor variables such as BMI, Age, Insulin, Pregnancies, etc., and a target variable named Outcome.
# Your task is to:
# Load the dataset using pandas.
# Separate independent and dependent variables.
# Split dataset into training and testing sets.
# Train a Random Forest Classifier.
# Predict patient outcomes.
# Evaluate performance using:
# Confusion Matrix
# Accuracy Score

In [16]:
df=pd.read_csv('https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/diabetes.csv')
df.head()

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [18]:
x=df.drop(columns='Outcome');
y=df['Outcome'];
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2);

In [19]:
dtree=DecisionTreeClassifier(criterion='entropy',max_depth=3);

In [21]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [24]:
prediction=dtree.predict([[1,180,90,20,0,30,0.245,45]])
print(prediction)

[1]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [26]:
cm=confusion_matrix(y_test,dtree.predict(x_test))
print("Confusion Matrix -\n",cm)

Confusion Matrix -
 [[83 16]
 [20 35]]

In [27]:
print(accuracy_score(y_test,dtree.predict(x_test)))

0.7662337662337663